-- Phase 1 schema: projects, pipeline runs, jobs (DAG nodes) and steps.
-- A run stores a snapshot of the pipeline YAML it was created from, so re-running
-- or auditing an old run is never affected by later edits to the pipeline file.

CREATE TABLE project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner           VARCHAR(100) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    default_branch  VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_project_owner_name UNIQUE (owner, name)
);

CREATE TABLE pipeline_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    run_number       INTEGER NOT NULL,
    pipeline_name    VARCHAR(100) NOT NULL,
    commit_sha       VARCHAR(40) NOT NULL,
    branch           VARCHAR(255) NOT NULL,
    status           VARCHAR(20) NOT NULL,
    definition_yaml  TEXT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at       TIMESTAMP WITH TIME ZONE,
    finished_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_run_number_per_project UNIQUE (project_id, run_number)
);

CREATE INDEX idx_run_project_created ON pipeline_run (project_id, created_at DESC);
CREATE INDEX idx_run_status ON pipeline_run (status);

CREATE TABLE job (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT NOT NULL REFERENCES pipeline_run (id) ON DELETE CASCADE,
    name             VARCHAR(64) NOT NULL,
    image            VARCHAR(255) NOT NULL,
    stage            INTEGER NOT NULL,
    status           VARCHAR(20) NOT NULL,
    attempt          INTEGER NOT NULL DEFAULT 0,
    max_attempts     INTEGER NOT NULL,
    timeout_minutes  INTEGER NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at       TIMESTAMP WITH TIME ZONE,
    finished_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_job_name_per_run UNIQUE (run_id, name)
);

-- The scheduler (Phase 2) polls for runnable jobs by status.
CREATE INDEX idx_job_status ON job (status);

CREATE TABLE job_dependency (
    job_id      BIGINT NOT NULL REFERENCES job (id) ON DELETE CASCADE,
    depends_on  VARCHAR(64) NOT NULL,
    PRIMARY KEY (job_id, depends_on)
);

CREATE TABLE step (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       BIGINT NOT NULL REFERENCES job (id) ON DELETE CASCADE,
    position     INTEGER NOT NULL,
    name         VARCHAR(255) NOT NULL,
    command      TEXT NOT NULL,
    status       VARCHAR(20) NOT NULL,
    exit_code    INTEGER,
    started_at   TIMESTAMP WITH TIME ZONE,
    finished_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_step_position UNIQUE (job_id, position)
);
